
services:
  db:
    image: postgres:15
    container_name: clinica_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clinica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: clinica_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/clinica
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: clinica_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
